apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apache-5
  namespace: feroz
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache

    spec:
      containers:
      - name: apache
        image: ferozfrk/apache:5
        ports:
        - containerPort: 80
